name: CD

on:
  push:
    branches:
      - master

jobs:
  deploy_gh_pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: master
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: latest
      - run: pnpm i --frozen-lockfile
      # build
      - run: npm run blog:build
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.AHH }}
        with:
          target_branch: gh-pages
          build_dir: blog/.vuepress/dist
          jekyll: false # 禁用 GitHub 默认开启的 jekyll 构建
          #fqdn: vuepress-theme-mini.wxsm.space # 自定义域名，需要时填写