name: CI

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: latest
      - run: pnpm i --frozen-lockfile
      - name: Unit tests
        run: npm run test
  docs_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: latest
      - run: pnpm i --frozen-lockfile
      - name: Build blog
        run: npm run blog:build